### ISSUE TITLE
你好，能否打包一份最新的0.06

### ISSUE THREAD

**Issue by Zyy-boop** [JustUndertaker/ComWeChatBotClient#11]
我看到[子协议错误](https://github.com/JustUndertaker/ComWeChatBotClient/pull/7)已经修复了但是最新的0.0.5并没有修复这个问题。

**Comment by Zyy-boop** [comment]
目前我测试了两个服务器，都会报这个错误，解决方式是卸载原来的运行库重新安装[这个链接的](https://www.microsoft.com/zh-cn/download/confirmation.aspx?id=53587)
![image](https://user-images.githubusercontent.com/74231782/230714709-95faea89-ac18-44fb-a704-fb114c675800.png)

**Comment by JustUndertaker** [comment]
忙到头秃了，没啥时间。。。

**Comment by Zyy-boop** [comment]
你用啥打包的，我打包老是缺这缺那...最后啥都不缺少了一大堆

**Comment by JustUndertaker** [comment]
你可以看workflows里面，用的是nuitka；
我看今天有没有时间发个版吧

**Comment by Zyy-boop** [comment]
欧克欧克，感谢！
