### ISSUE TITLE
对于哔哩哔哩的分享消息无法生成 MessageEvent

### ISSUE THREAD

**Issue by VXenomac** [JustUndertaker/ComWeChatBotClient#13]

**Comment by JustUndertaker** [comment]
你确定吗，我这边测试是有消息的哦。

**Comment by JustUndertaker** [comment]
> 你确定吗，我这边测试是有消息的哦。

04-16 09:35:57 [SUCCESS] wechatbot_client | WeChat Manager | 生成事件[PrivateMessageEvent]:{'id': 'f39c12b7-14d5-4e33-8451-be1095ebffad', 'time': 1681608956.0, 'type': 'message', 'detail_type': 'private', 'sub_type': '', 'self': {'platform': 'wechat', 'user_id': 'wxid_se3fgulqwuxk22'}, 
'message_id': '358789378057285744', 'message': [MessageSegment(type='wx.app', data={'appid': 'gh_cd19667c4224@app', 'title': 'B站到底应该如何逆天改命？做了四年UP主的一些感想。', 'url': 'https://mp.weixin.qq.com/mp/waerrpage?appid=wx7564fd5313d24844&type=upgrade&upgradetype=3#wechat_redirect'})], 'alt_message': '', 'user_id': 'wxid_efvl5e3e7exo22'}
