### ISSUE TITLE
大图片自动断开

### ISSUE THREAD

**Issue by wangyu1997** [JustUndertaker/ComWeChatBotClient#2]
你好，我刚才测试了一下Comwechat的图片上传功能，由于client和nonebot不在一台机器，所以采用的data传输模式
当图片过大的时候ws自动断开，且图片发送失败，请问这个问题是bug吗？ 

![image](https://user-images.githubusercontent.com/15991233/229344919-21870d57-1ac6-4631-bec0-547c749bc7c1.png)

![image](https://user-images.githubusercontent.com/15991233/229344913-e11d9f2d-a722-47b7-b830-1d0fba72bcd1.png)

**Comment by JustUndertaker** [comment]
原因是websocket的默认buffer只有1m，后续改成可配得了
