### ISSUE TITLE
[OBv12实现] 连接后缺失 meta.status_update 事件

### ISSUE THREAD

**Issue by FYWinds** [JustUndertaker/ComWeChatBotClient#26]
## 期望结果
在连接后立刻发送`StatusUpdateMetaEvent`更新信息，以便Onebot应用将对应Bot实例化
参考 [Onebot V12 文档](https://12.onebot.dev/interface/meta/events/#metastatus_update)

## 目前表现
未发送此事件，导致部分Onebot应用无法正常工作
示例[nonebot onebot-adapter v12](https://github.com/nonebot/adapter-onebot/blob/master/nonebot/adapters/onebot/v12/adapter.py#L351-L352)

## 复现方式
1. 正常启动`ComWeChatBotClient`与Onebot应用
2. Onebot应用无法获取连接的Bot信息

## 可能的解决方案(ws)
在 [此处](https://github.com/JustUndertaker/ComWeChatBotClient/blob/main/wechatbot_client/wechat/adapter.py#L131) 发送连接事件后，及时发送 [meta.status_update](https://12.onebot.dev/interface/meta/events/#metastatus_update) 事件

**Comment by FYWinds** [comment]
## 可能的相关问题
* 缺少状态更新，如客户端掉线后的信息更新

**Comment by jackycaf** [comment]
遇到同样问题，nonebot+ComWeChatBotClient启动并连接成功后，bot未能初始化，无法执行诸如：get_friend_list等接口指令。只有接收到新消息，bot才被初始化，

**Comment by JustUndertaker** [comment]
onebot适配器加了链接复用，需要手动更新StatusUpdate才会链接。
