### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Kloping** [JustUndertaker/ComWeChatBotClient#3]
![image](https://user-images.githubusercontent.com/87743020/229761313-cefb7038-cce7-4c22-8167-93c98a830f51.png)

**Comment by JustUndertaker** [comment]
目前不清楚发生的原因，因为我没有在powershell试验过= =。
你可以直接双击install.bat安装试试。

**Comment by Kloping** [comment]
![image](https://user-images.githubusercontent.com/87743020/229812102-5d0308df-c118-4de8-96be-266230517bd3.png)
那个解决了 但是

**Comment by JustUndertaker** [comment]
nuitka打包问题，先把需要定时的任务关了吧，预计下个版本解决

**Comment by Kloping** [comment]
ok

**Comment by Kloping** [comment]
![image](https://user-images.githubusercontent.com/87743020/229832970-2d174530-d0b8-4e16-9045-06491a5567c2.png)

**Comment by Kloping** [comment]
> ![image](https://user-images.githubusercontent.com/87743020/229832970-2d174530-d0b8-4e16-9045-06491a5567c2.png)

目前用NoneBot onebot12 连接

**Comment by JustUndertaker** [comment]
草，nuitka是真难用

**Comment by Kloping** [comment]
兄弟怎么搞
