### ISSUE TITLE
请问http如何调用,小伙伴能否给个例子?

### ISSUE THREAD

**Issue by zsq2010** [JustUndertaker/ComWeChatBotClient#53]

**Comment by zsq2010** [comment]
比如,http://10.211.55.3:8000/send_private_msg之类的?

**Comment by barryblueice** [comment]
请提供更为详细的诉求，例如你想要干什么

**Comment by zsq2010** [comment]
> 请提供更为详细的诉求，例如你想要干什么

感谢回复!!

目标:我想使用http的方式来调用功能,比如发送信息,
方案和困境:经过阅读,我并没有能力拼接一个http请求,以发送私信或群组消息
需求:我需要一个http请求的例子
比如,使用curl,golang(最好)

**Comment by zsq2010** [comment]
简单的说想使用http服务,并需要一个调用的例子(我拼来拼去,这个http凑不成功,非常困扰我)

**Comment by xinxinyihao** [comment]
> 简单的说想使用http服务,并需要一个调用的例子(我拼来拼去,这个http凑不成功,非常困扰我)

![image](https://github.com/JustUndertaker/ComWeChatBotClient/assets/41506567/f36e377f-404d-446c-bfc8-ccb373d2724a)
这么调用的

**Comment by zsq2010** [comment]
非常感谢您,在下回头试试!! (鞠躬)

**Comment by zsq2010** [comment]
> > 简单的说想使用http服务,并需要一个调用的例子(我拼来拼去,这个http凑不成功,非常困扰我)
> 
> ![image](https://private-user-images.githubusercontent.com/41506567/313588249-f36e377f-404d-446c-bfc8-ccb373d2724a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMDQ5MjYsIm5iZiI6MTcxMTIwNDYyNiwicGF0aCI6Ii80MTUwNjU2Ny8zMTM1ODgyNDktZjM2ZTM3N2YtNDA0ZC00NDZjLWJmYzgtY2NiMzczZDI3MjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDE0MzcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NzI0MTMzM2UwNTJmMThhMGI5YTlkMTAyNGZjMmE2ODMyZjQxOWE0OWFmNWRiMmY1ZGYwYjQzZDEwNjhiYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tm2eL3G5Sin-dEq6Hxhw0CcykfopZlizuBCrWi0OpvY) 这么调用的



> > 简单的说想使用http服务,并需要一个调用的例子(我拼来拼去,这个http凑不成功,非常困扰我)
> 
> ![image](https://private-user-images.githubusercontent.com/41506567/313588249-f36e377f-404d-446c-bfc8-ccb373d2724a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMDUwMzcsIm5iZiI6MTcxMTIwNDczNywicGF0aCI6Ii80MTUwNjU2Ny8zMTM1ODgyNDktZjM2ZTM3N2YtNDA0ZC00NDZjLWJmYzgtY2NiMzczZDI3MjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDE0Mzg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZjBkNDZmOWMyYjA0MDk4NDBkMDc5ZjRlYjQ1NGUyY2EyZGY1NWFlMmZhNjZkZTQ3ZmY1OWU1NGY3YjM4NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IQyDs5XHbx90ka3K-3EqS6AlS3sr1sdpthgcej164f8) 这么调用的

非常感谢您,在下回头试试!! (鞠躬)
