### ISSUE TITLE
请求的多项数据为null

### ISSUE THREAD

**Issue by Kloping** [JustUndertaker/ComWeChatBotClient#6]
![image](https://user-images.githubusercontent.com/87743020/230405744-e98c0ef1-a36b-4df5-a728-d7150001ce73.png)
这属于正常现象吗

**Comment by JustUndertaker** [comment]
真说原理，是因为这些数据都是查询的本地sqlite数据库，新登录的号没有同步到这些数据属实正常，需要你进行点击头像等操作才会刷新数据。

**Comment by Kloping** [comment]
> 真说原理，是因为这些数据都是查询的本地sqlite数据库，新登录的号没有同步到这些数据属实正常，需要你进行点击头像等操作才会刷新数据。

好的
